name: commitlint
on:
  pull_request:
permissions:
  contents: read
jobs:
  commitlint:
    permissions:
      contents: read
    uses: unabandoned/.github/.github/workflows/reusable-commitlint.yml@461710fd515f1e40157994d7e11f9e3605db0626 # main
