name: release-please
on:
  push:
    branches: [master]
permissions:
  contents: read
jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    uses: unabandoned/.github/.github/workflows/reusable-release-please.yml@461710fd515f1e40157994d7e11f9e3605db0626 # main
    secrets: inherit
